#!/bin/csh
# VPN Init file 

set wlangate = `ip route show to 0/0 | grep -e wlan -e wlp | cut -d ' ' -f3`
set vpngate = `ip addr sh dev ppp0 | grep peer | cut -d ' ' -f8 | cut -d '/' -f1`

ip route del 0.0.0.0/1 via $vpngate
ip route del 128.0.0.0/1 via $vpngate

